name: Create Card in GitHub Project

on:
  issues:
    types: [opened]

jobs:
  move-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: "PexinxaReactApp"
          column: "Status"
          status: "Planning ⛷️" 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
