name: Create Draft Issue in GitHub Project

on:
  workflow_dispatch:
    inputs:
      issue-title:
        description: 'Título da Issue'
        required: true
      issue-body:
        description: 'Descrição da Issue'
        required: true
        
jobs:
  create-draft-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create issue with Draft label
        uses: peter-evans/create-issue@v2
        with:
          title: ${{ github.event.inputs.issue-title }}
          body: ${{ github.event.inputs.issue-body }}
          labels: 'Draft'

      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: "PexinxaReactApp"
          column: "Status"
          status: "Planning ⛷️" 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
