name: Create Card in GitHub Project

on:
  issues:
    types: [opened]

jobs:
  move-card:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Change directory to subfolder
        run: cd ./pexinxa-front

      - uses: alex-page/github-project-automation-plus@v0.3.0
        with:
          project: "PexinxaReactApp"
          column: "Status"
          status: "Planning ⛷️" 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
